# Generated by Django 3.2.16 on 2022-10-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weesh_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weesh',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ELECTRONICS'), (1, 'FURNITURE'), (2, 'VOLUNTEER_SERVICE'), (3, 'FUNDS'), (4, 'EDUCATIONAL_MATERIALS'), (5, 'OTHERS')]),
        ),
    ]
