# Generated by Django 3.2.16 on 2022-11-05 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weesh_item', '0002_alter_weesh_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='weesh',
            name='fulfiled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weesh',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='weesh',
            name='quantity_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='weesh',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weesh',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FulfilWeesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weesh_item.weesh')),
            ],
        ),
    ]
