# Generated by Django 3.2.16 on 2022-10-15 11:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(max_length=50)),
                ('address_line_two', models.CharField(max_length=50)),
                ('country', models.CharField(default='Nigeria', max_length=10)),
                ('city', models.CharField(default='Ibadan', max_length=20)),
                ('state', models.CharField(default='Oyo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_of_incorporation', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizationcategory')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.documents')),
            ],
        ),
    ]
